swagger: '2.0'
info:
  title: Bytemark Authentication API
  description: Authenticates users
  version: '1.0.0'
host: auth.bytemark.co.uk
basePath: ''
schemes:
  - https
consumes:
  - application/json
produces:
  - text/plain; charset=utf-8
paths:
  /session:
    post:
      operationId: authenticateUser
      summary: Creates a session
      description: Returns a session ID if a valid user name and password are provided
      parameters:
        - name: user
          in: body
          schema:
            required:
              - username
              - password
            properties:
              username:
                type: string
              password:
                type: string
              yubikey:
                type: string
      responses:
        200:
          description: Session ID
          schema:
            type: string
        400:
          description: Authenticiation failed
        default:
          description: Unexpected error
  
